import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Pagination } from "@/components/ui/pagination";
import { ThemeProvider } from "next-themes";
import { Header } from "./_components/Header";
import { Footer } from "./_components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="white">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
